[build]
  command = "npm run build --prefix frontend"
  publish = "frontend/dist"

[functions]
  directory = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
